### ISSUE TITLE
Volume names can be too long and invalid

### ISSUE THREAD

**Issue by maybedino** [cdk8s-team/cdk8s-plus#1130]
Names can be up to 63 characters, so when names are generated from the node path, they are trimmed. Otherwise the manifest would be invalid.

When you create a volume from a config map, and the name is not set, the default will be `configmap-${configMap.name}`:

https://github.com/cdk8s-team/cdk8s-plus/blob/788128a6d58901c3b4bb42dc0ef62f396628d019/src/volume.ts#L131

But the name of the config map can be the generated name. So now the length can be up to 10+63=73 (length of 'configmap-' + 63) because the length of the name is not checked again. That actually happens quite easily if you have nested constructs and don't set names. The same can happen for other volume functions, `fromAwsElasticBlockStore`, `fromAzureDisk`, etc. 

Maybe a better solution would be using either the ID of the volume, or the ID of the config map instead of the config map name? Or maybe not require a name for the Volume, remove the defaults and generate it from the node path like other names?

**Comment by iliapolo** [comment]
Thanks for reporting this @maybedino - i've created a PR with a fix. Ideally I would agree that generating the volume name from its node path would be the solution. This logic was actually written I believe before Volumes were constructs, they used to be just regular classes. Its a bit tricky to implement though because we need the name during instantiation, and we need to instantiate to get the name..it can be done but not really necessary, especially because it would be a breaking change.
