### ISSUE TITLE
Add support for Kubernetes `v1.28` and `v1.29`

### ISSUE THREAD

**Issue by DaxServer** [cdk8s-team/cdk8s-plus#3302]
### Description of the feature or enhancement:
Add support for Kubernetes `v1.28` and `v1.29`

### Use Case:
This would integrate the K8s latest release with cdk8s+

### Other:

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MatthewCane** [comment]
Can we have an update on this issue please maintainers? We already have Kubernetes 1.29 and cdk8s-plus is still at 1.27.

**Comment by watkinsmike** [comment]
This makes me reluctant to use this project. I know Kubernetes releases come fast, but it has been 6 months since the release of 1.28 and there appears to be no one keeping this up to date. If there were to be an actual issue instead of just slow release cadence then I would not believe there to be much help resolving it or fixes.

**Comment by serhatcetinkaya** [comment]
any updates on this ? tagging owners to make sure they see it:
@iliapolo
@Chriscbr
@tabern

**Comment by Hazzard17h** [comment]
Are they released now?
https://github.com/cdk8s-team/cdk8s-plus/releases/tag/cdk8s-plus-28%2Fv2.0.0
https://github.com/cdk8s-team/cdk8s-plus/releases/tag/cdk8s-plus-29%2Fv2.0.0

**Comment by DaxServer** [comment]
The versions are released. Here's the new link to issue requesting support for `v1.30.0`: https://github.com/cdk8s-team/cdk8s-plus/issues/4137
