### ISSUE TITLE
Create rolling release not tied to specific k8s version

### ISSUE THREAD

**Issue by awlsring** [cdk8s-team/cdk8s-plus#4038]
I wonder if having releases of cdk8s tied to k8s versioning is the correct way to go for this project. Not much seems to change between versions as the constructs exposed here are mostly on stable resources.

It seems to have the following down sides
- manual effort every 6 months to bump, branch, and deprecate
- bug / patch changes must be pushed maintained versions
- 3rd party construct libraries must also branch for cdk8s plus version or re implement these constructs themselves
- communicates users can use only if their k8s version is supported

What if there was a "rolling release" of this library that implicitly targeted support of the past 3 releases of k8s and was only concerned about making compatible changes within those? 

Since at the end of the day this is just a fancy YAML generator, version specific changes could be implemented by having the constructs have a `k8sSyntaxVersion` property that defines how the YAML object get written. This could explicitly be set on a per object basis or could be determined via a `K8S_SYNTAX_VERSION` shell variable that defaults to the most current K8S version.

Having this would decrease project maintenance, reduce versioning confusion, and would make of 3rd party construct libraries more feasible. 

My familiarity with the implementation of this project is not incredibly deep so there may be some thing I'm not considering here. Does this seem feasible?

**Comment by iliapolo** [comment]
We considered this before coupling the library with a k8s version. The main reason not to have a rolling release were compile time validations. 

With a rolling release, there is no way to have compile time error when a user uses a property/resource that doesn't exist in the k8s version they are targeting. Runtime validations are also tricky to implement because we would have to mark every resource/property with the k8s versions it supports. This effectively means that validations are moved to deploy time, which is what we wanted to avoid. 

I agree that this poses a burden on project maintenance. We decided to take that "hit" in order to provide a better authoring experience. I also agree that it makes it a little confusing at first to choose which library should one be using, but once that decision is made, and the process is established, we feel the continuous authoring experience is better. 

> Not much seems to change between versions as the constructs exposed here are mostly on stable resources.

True, but even stable resources add features to it, that might not be available on earlier k8s versions.
