### ISSUE TITLE
Upgrading from 1.x to 2.x with python binding

### ISSUE THREAD

**Issue by christallire** [cdk8s-team/cdk8s-plus#991]
Hey guys, I've been trying to upgrade cdk8s plus project with latest version of package due to new functionalities (e.g tolerate)

The problem I'm having is, many of binded function prototype is changed to supply positional arguments like below:
```
serviceAccount = kplus.ServiceAccount.from_service_account_name('docker-pull')
TypeError: ServiceAccount.from_service_account_name() missing 2 required positional arguments: 'id' and 'name'
```

Could you please confirm this change is intended?
I've checked through released packages and 2.0.0-b11 doesn't require these parameters but others up and higher is.

Thanks!

**Comment by iliapolo** [comment]
@christallire Apologies for the (very) delayed response. Yes this was an intentional change we made just before releasing the library out of beta. Here is the PR that introduced it, it contains some reasoning behind the change. 

https://github.com/cdk8s-team/cdk8s-plus/issues/747

Did you manage to eventually upgrade and use the new version?
